function $(s){return document.querySelector(s)}
function esc(s){return String(s||'').replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function storeGet(k){try{return JSON.parse(localStorage.getItem(k)||'[]')}catch(e){return[]}}
function storeSet(k,v){try{localStorage.setItem(k,JSON.stringify(v))}catch(e){}}
var S={v:'home',era:null,comp:null,q:'',level:'all',fav:storeGet('pa_fav'),learn:storeGet('pa_learn'),wtcBook:'all',wtcQ:''};
var PHOTO={};
function all(){var a=[];DATA.forEach(function(e){e.c.forEach(function(c){c.w.forEach(function(x){a.push(Object.assign({},x,{id:x.id,title:x.t,level:x.lv,comp:c.n,cid:c.id,era:e.n,eid:e.id,wiki:c.wiki}))})})});return a}
function era(id){return DATA.filter(function(x){return x.id===id})[0]}
function comp(id){var r;DATA.forEach(function(e){e.c.forEach(function(c){if(c.id===id)r=c})});return r}
function work(id){return all().filter(function(x){return x.id===id})[0]}
function dots(n){var s='<span class="dots">';for(var i=0;i<10;i++)s+='<i class="dot '+(i<n?'on':'')+'"></i>';return s+'</span>'}
function toast(t){var x=$('#toast');x.textContent=t;x.classList.add('on');setTimeout(function(){x.classList.remove('on')},1500)}
function nav(){document.querySelectorAll('.nav button').forEach(function(b){b.classList.toggle('on',b.dataset.v===S.v)})}
function go(v){S.v=v;render()}
function render(){nav();if(S.v==='home')home();if(S.v==='era')eraView();if(S.v==='comp')compView();if(S.v==='fav')listView('Избранное',S.fav,'Отмечайте произведения сердцем.');if(S.v==='learn')listView('Хочу выучить',S.learn,'Добавляйте произведения в план занятий.');if(S.v==='wtc')wtcView();loadPhotos();try{scrollTo({top:0,behavior:'smooth'})}catch(e){scrollTo(0,0)}}
function photoUrl(slug,cb){if(PHOTO[slug])return cb(PHOTO[slug]);fetch('https://en.wikipedia.org/api/rest_v1/page/summary/'+encodeURIComponent(slug)).then(function(r){if(!r.ok)throw 0;return r.json()}).then(function(d){var p=d.thumbnail&&d.thumbnail.source?d.thumbnail.source:'';PHOTO[slug]={src:p,page:(d.content_urls&&d.content_urls.desktop&&d.content_urls.desktop.page)||('https://en.wikipedia.org/wiki/'+slug)};cb(PHOTO[slug])}).catch(function(){PHOTO[slug]={src:'',page:'https://en.wikipedia.org/wiki/'+slug};cb(PHOTO[slug])})}
function loadPhotos(){document.querySelectorAll('[data-wiki]').forEach(function(img){var slug=img.dataset.wiki;if(img.dataset.loading)return;img.dataset.loading='1';photoUrl(slug,function(p){if(p.src){img.onload=function(){img.classList.add('loaded')};img.src=p.src}var credit=img.closest('.cover')&&img.closest('.cover').querySelector('.photo-link');if(credit)credit.href=p.page})});var hp=document.querySelector('.hero-photo[data-wiki]');if(hp&&!hp.dataset.loading){hp.dataset.loading='1';photoUrl(hp.dataset.wiki,function(p){if(p.src){hp.onload=function(){hp.style.display='block'};hp.src=p.src}var cr=document.querySelector('.photo-credit');if(cr)cr.href=p.page})}}
function controls(){return'<div class="controls"><input id="q" placeholder="Найти произведение или композитора…"><select id="level"><option value="all">Любая сложность</option><option value="easy">1–4: начинающий</option><option value="mid">5–7: средний</option><option value="hard">8–10: продвинутый</option></select></div><div id="results"></div>'}
function bindControls(){var q=$('#q'),l=$('#level');q.value=S.q;l.value=S.level;q.oninput=function(){S.q=this.value;results()};l.onchange=function(){S.level=this.value;results()}}
function match(w){var q=S.q.toLowerCase().trim(),ok=!q||(w.title+' '+w.comp+' '+w.era+' '+w.mood+' '+w.year+' '+w.place+' '+w.fact).toLowerCase().indexOf(q)>-1;return ok&&(S.level==='all'||S.level==='easy'&&w.level<=4||S.level==='mid'&&w.level>=5&&w.level<=7||S.level==='hard'&&w.level>=8)}
function results(){var a=all().filter(match);$('#results').innerHTML=S.q||S.level!=='all'?rows(a):'';bindWorks()}
function home(){$('#main').innerHTML='<section class="hero"><div class="ey">Навигатор по фортепианной музыке</div><h1>Не только ноты — история музыки.</h1><p>Эпохи, портреты композиторов, обстоятельства создания произведений, музыкальный анализ и знаковые интерпретации.</p><div class="actions"><button class="primary" id="start">Выбрать эпоху</button><button class="secondary" id="openWtc">Открыть ХТК Баха</button><button class="secondary" id="pick">Случайное произведение</button></div></section>'+controls()+'<section class="feature-card"><div><span class="feature-kicker">Новый подробный разбор</span><h2>Рахманинов: Прелюдия до-диез минор</h2><p>Крупная форма A–B–A′, фактура, драматургия, исполнительские задачи, история создания и собственные слова композитора.</p></div><button class="primary" id="rachAnalysis">Открыть анализ</button></section><div class="head" id="eras"><div><h2>Музыкальные эпохи</h2><p>От барокко до современной неоклассики</p></div><span class="count">'+DATA.length+' разделов</span></div><section class="grid">'+DATA.map(function(e,i){return'<button class="era" data-era="'+e.id+'"><b>0'+(i+1)+'</b><h3>'+e.n+'</h3><p>'+e.y+'<br>'+e.d+'</p><span class="arrow">→</span></button>'}).join('')+'</section><div class="head"><div><h2>Для первого просмотра</h2><p>Откройте карточку и нажмите ⓘ у произведения</p></div></div><section class="grid">'+['chopin','bach','rach'].map(function(id){return card(comp(id))}).join('')+'</section>';$('#start').onclick=function(){$('#eras').scrollIntoView({behavior:'smooth'})};$('#pick').onclick=randomInfo;$('#openWtc').onclick=function(){go('wtc')};$('#rachAnalysis').onclick=openAnalysis;document.querySelectorAll('[data-era]').forEach(function(b){b.onclick=function(){S.era=this.dataset.era;go('era')}});bindControls();bindComps()}
function card(c){var e;DATA.forEach(function(x){if(x.c.indexOf(c)>-1)e=x});return'<article class="card"><div class="cover"><img alt="Портрет: '+esc(c.n)+'" data-wiki="'+esc(c.wiki)+'"><div class="cover-fallback">'+esc(c.n.split(' ').pop())+'</div><a class="photo-link" aria-label="Источник фотографии" target="_blank" rel="noopener"></a></div><div class="body"><span class="pill">'+e.n+'</span><span class="pill">'+c.k+'</span><h3>'+c.n+'</h3><p>'+c.a+'</p><button class="open opencomp" data-c="'+c.id+'">'+c.w.length+' произведений</button></div></article>'}
function bindComps(){document.querySelectorAll('.opencomp').forEach(function(b){b.onclick=function(){S.comp=this.dataset.c;DATA.forEach(function(e){e.c.forEach(function(c){if(c.id===S.comp)S.era=e.id})});go('comp')}})}
function eraView(){var e=era(S.era);$('#main').innerHTML='<div class="crumb"><button id="home">Обзор</button><span>›</span><span>'+e.n+'</span></div><section class="hero"><div class="ey">'+e.y+'</div><h1>'+e.n+'</h1><p>'+e.d+'</p></section><div class="head"><div><h2>Композиторы</h2><p>Выберите автора</p></div><span class="count">'+e.c.length+'</span></div><section class="grid">'+e.c.map(card).join('')+'</section>';$('#home').onclick=function(){go('home')};bindComps()}
function compView(){var c=comp(S.comp),e=era(S.era);var ww=c.w.map(function(x){return Object.assign({},x,{id:x.id,title:x.t,level:x.lv,comp:c.n})});$('#main').innerHTML='<div class="crumb"><button id="home">Обзор</button><span>›</span><button id="back">'+e.n+'</button><span>›</span><span>'+c.n+'</span></div><section class="hero with-photo"><img class="hero-photo" data-wiki="'+esc(c.wiki)+'" alt="Портрет: '+esc(c.n)+'" style="display:none"><a class="photo-credit" target="_blank" rel="noopener">Фото: Wikipedia / Wikimedia</a><div class="ey">'+c.k+' · '+c.l+'</div><h1>'+c.n+'</h1><p>'+c.a+'</p></section><div class="disclaimer">Даты и места некоторых произведений известны приблизительно. «Знаковые исполнения» — не рейтинг, а записи разных исполнительских школ.</div><div class="head"><div><h2>Произведения</h2><p>ⓘ — история; ≡ — музыкальный анализ; ♫ — ноты</p></div></div><section class="works">'+rows(ww)+'</section>';$('#home').onclick=function(){go('home')};$('#back').onclick=function(){go('era')};bindWorks()}
function rows(a){if(!a.length)return'<div class="empty">Ничего не найдено.</div>';return a.map(function(w){var analysis=w.id==='r1'?'<button class="mini analysis" data-id="'+w.id+'" aria-label="Музыкальный анализ">≡</button>':'';return'<article class="work"><div><div class="wt">'+esc(w.title)+dots(w.level)+'</div><div class="ws">'+(w.comp?esc(w.comp)+' · ':'')+esc(w.time)+' · '+esc(w.mood)+'</div><div class="yearline"><span class="tag">'+esc(w.year)+'</span><span class="tag">'+esc(w.age)+'</span></div></div><div class="wa"><button class="mini fav '+(S.fav.indexOf(w.id)>-1?'on':'')+'" data-id="'+w.id+'" aria-label="В избранное">♡</button><button class="mini learn '+(S.learn.indexOf(w.id)>-1?'on':'')+'" data-id="'+w.id+'" aria-label="Хочу выучить">✓</button><button class="mini info" data-id="'+w.id+'" aria-label="История произведения">ⓘ</button>'+analysis+'<button class="mini scorebtn" data-id="'+w.id+'" aria-label="Ноты">♫</button></div></article>'}).join('')}
function bindWorks(){document.querySelectorAll('.fav').forEach(function(b){b.onclick=function(){toggle('fav',this.dataset.id)}});document.querySelectorAll('.learn').forEach(function(b){b.onclick=function(){toggle('learn',this.dataset.id)}});document.querySelectorAll('.info').forEach(function(b){b.onclick=function(){openInfo(this.dataset.id)}});document.querySelectorAll('.analysis').forEach(function(b){b.onclick=openAnalysis});document.querySelectorAll('.scorebtn').forEach(function(b){b.onclick=function(){openScore(this.dataset.id)}})}
function toggle(k,id){var a=S[k],i=a.indexOf(id);if(i>-1){a.splice(i,1);toast('Удалено')}else{a.push(id);toast('Добавлено')}storeSet('pa_'+k,a);render()}
function listView(title,ids,empty){var a=ids.map(work).filter(Boolean);$('#main').innerHTML='<section class="hero"><div class="ey">Личная коллекция</div><h1>'+title+'</h1><p>'+empty+'</p></section><div class="head"><div><h2>'+(a.length?'Ваш список':'Пока пусто')+'</h2></div><span class="count">'+a.length+'</span></div><section class="works">'+(a.length?rows(a):'<div class="empty">'+empty+'</div>')+'</section>';bindWorks()}
function showModal(title,body){$('#mt').textContent=title;$('#modalContent').innerHTML=body;$('#modal').classList.add('on')}
function openInfo(id){var w=work(id);var players=w.players.map(function(p){return'<span class="player">'+esc(p)+'</span>'}).join('');var extra=id==='r1'?'<div class="author-box"><strong>Что сам Рахманинов думал об этой прелюдии</strong><p>'+esc(RACH_ANALYSIS.author)+'</p><button class="analysis-link" id="fromInfoAnalysis">Открыть полный музыкальный анализ →</button></div>':'';showModal('История произведения','<div class="details"><div class="detail-title">'+esc(w.title)+'</div><div class="detail-sub">'+esc(w.comp)+' · сложность '+w.level+'/10 · '+esc(w.time)+'</div><div class="meta-grid"><div class="meta"><small>Год создания</small><b>'+esc(w.year)+'</b></div><div class="meta"><small>Возраст автора</small><b>'+esc(w.age)+'</b></div><div class="meta"><small>Где написано</small><b>'+esc(w.place)+'</b></div></div><div class="fact"><strong>История и интересный факт</strong>'+esc(w.fact)+'</div>'+extra+'<div class="interpret"><h3>Знаковые исполнения</h3><p>Записи для сравнения темпа, фразировки, педали и характера. Это не список «лучших».</p><div class="players">'+players+'</div></div><a class="source-link" href="'+esc(w.src)+'" target="_blank" rel="noopener">Источник исторической справки ↗</a></div>');var b=$('#fromInfoAnalysis');if(b)b.onclick=openAnalysis}
function openAnalysis(){var a=RACH_ANALYSIS;var sections=a.sections.map(function(s){return'<div class="form-row"><div class="form-name">'+esc(s.name)+'<small>'+esc(s.bars)+'</small></div><div class="form-text">'+esc(s.text)+'</div></div>'}).join('');var tasks=a.tasks.map(function(t){return'<li>'+esc(t)+'</li>'}).join('');var sources=a.sources.map(function(s){return'<a class="source-link compact" href="'+esc(s.url)+'" target="_blank" rel="noopener">'+esc(s.label)+' ↗</a>'}).join('');showModal('Музыкальный анализ','<div class="details analysis-page"><div class="detail-title">'+esc(a.title)+'</div><div class="detail-sub">Сергей Рахманинов · аналитическая карточка для пианиста</div><div class="analysis-summary"><div><small>Жанр</small><b>'+esc(a.genre)+'</b></div><div><small>Крупная форма</small><b>'+esc(a.form)+'</b></div></div><h3>Схема формы</h3><div class="form-map">'+sections+'</div><div class="analysis-columns"><section><h3>Фактура</h3><p>'+esc(a.texture)+'</p></section><section><h3>Драматургия</h3><p>'+esc(a.dramaturgy)+'</p></section></div><section class="history-box"><h3>История создания</h3><p>'+esc(a.history)+'</p></section><section class="author-box"><h3>Что говорил и думал автор</h3><p>'+esc(a.author)+'</p></section><section><h3>Исполнительские задачи</h3><ol class="task-list">'+tasks+'</ol></section><div class="analysis-note">Разбор показывает один распространённый аналитический подход. Границы внутренних подразделов и трактовка последних тактов как части репризы или коды могут различаться у исследователей.</div><div class="source-stack">'+sources+'</div></div>')}
function openScore(id){var w=work(id);var lock=w.free?'Демонстрационная страница. В рабочей версии здесь будет проверенный свободный PDF или легальная ссылка на источник.':'Ноты защищены авторским правом либо требуют отдельной проверки редакции. Здесь будет ссылка на официальную покупку или лицензированная версия.';var body='<div class="score"><div class="notice">'+lock+'</div><div class="sheet"><h3>'+esc(w.title)+'</h3><p>'+esc(w.comp)+'</p>';if(!w.free)body+='<p style="font-size:45px;margin-top:120px">🔒</p>';else{var p=['♩ ♪ ♫ ♩ ♩ ♪ ♫','♫ ♩ ♪ ♩ ♫ ♪ ♩','♩ ♩ ♫ ♪ ♩ ♫ ♪','♪ ♫ ♩ ♪ ♩ ♩ ♫','♫ ♪ ♩ ♫ ♪ ♩ ♪'];p.forEach(function(x){body+='<div class="staff"><div class="notes">'+x+'</div></div>'})}showModal(w.title,body+'</div></div>')}
function wtcView(){var q=S.wtcQ.toLowerCase().trim();var items=WTC_DATA.filter(function(x){return(S.wtcBook==='all'||String(x.book)===S.wtcBook)&&(!q||(x.key+' '+x.bwv+' '+x.no).toLowerCase().indexOf(q)>-1)});$('#main').innerHTML='<section class="hero wtc-hero"><div class="ey">Иоганн Себастьян Бах · BWV 846–893</div><h1>Хорошо темперированный клавир</h1><p>Две книги, 48 пар «прелюдия + фуга» и 96 отдельных пьес во всех мажорных и минорных тональностях.</p><div class="wtc-stats"><span><b>2</b> книги</span><span><b>48</b> пар</span><span><b>96</b> пьес</span></div></section><div class="disclaimer">В одном месте собраны обе книги и все BWV. Музыка Баха находится в общественном достоянии, однако конкретные современные редакции, аппликатура и оформление могут охраняться авторским правом. Поэтому сейчас приложение ведёт на архивные страницы с выбором легальных изданий.</div><div class="wtc-controls"><input id="wtcQ" placeholder="Поиск: тональность или BWV"><select id="wtcBook"><option value="all">Обе книги</option><option value="1">Книга I — 1722</option><option value="2">Книга II — около 1740</option></select></div><div class="book-intro"><h2>Зачем Бах создал ХТК</h2><p>Первая книга была завершена в 1722 году. На титульном листе Бах обозначил её как материал для пользы музыкальной молодёжи и для занятия уже опытных музыкантов. Вторая книга была собрана примерно двумя десятилетиями позже.</p></div><section class="wtc-list">'+wtcRows(items)+'</section>';var qi=$('#wtcQ'),bi=$('#wtcBook');qi.value=S.wtcQ;bi.value=S.wtcBook;qi.oninput=function(){S.wtcQ=this.value;wtcView()};bi.onchange=function(){S.wtcBook=this.value;wtcView()}}
function wtcRows(items){if(!items.length)return'<div class="empty">Ничего не найдено.</div>';return items.map(function(x){return'<article class="wtc-item"><div class="wtc-num">'+String(x.no).padStart(2,'0')+'</div><div class="wtc-main"><div class="wtc-title">Прелюдия и фуга · '+esc(x.key)+'</div><div class="wtc-meta">Книга '+x.book+' · BWV '+x.bwv+'</div></div><div class="wtc-actions"><a href="'+esc(x.story)+'" target="_blank" rel="noopener" title="История и исполнение">ⓘ</a><a href="'+esc(x.score)+'" target="_blank" rel="noopener" title="Ноты на IMSLP">♫</a></div></article>'}).join('')}
function randomInfo(){var a=all();openInfo(a[Math.floor(Math.random()*a.length)].id)}
$('#close').onclick=function(){$('#modal').classList.remove('on')};$('#modal').onclick=function(e){if(e.target===this)this.classList.remove('on')};$('#random').onclick=randomInfo;document.querySelectorAll('.nav button').forEach(function(b){b.onclick=function(){S.era=null;S.comp=null;go(this.dataset.v)}});render();